apiVersion: v1
kind: ConfigMap
metadata:
  name: flowcontrol-legacy
  namespace: compat-demo
data:
  flowschema-v1beta2.yaml: |
    apiVersion: flowcontrol.apiserver.k8s.io/v1beta2
    kind: FlowSchema
    metadata:
      name: compat-demo-v1beta2-flowschema
    spec:
      matchingPrecedence: 1000
      priorityLevelConfiguration:
        name: exempt
      rules:
      - resourceRules:
        - apiGroups: ["*"]
          resources: ["*"]
          verbs: ["*"]
        subjects:
        - kind: Group
          group:
            name: system:authenticated